version: '3'

services:
  postgresql:
    image: ionetraining/postgresql:9.6.2
    networks:
      - database
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: ionetraining/pgadmin:4v2.1
    ports:
      - "5050:5050"
    depends_on:
      - postgresql
    networks:
      - database

volumes:
  pgdata:

networks:
  database:
